"""added session_cron_job table

Revision ID: eb35327bce1f
Revises: ed14becb7526
Create Date: 2025-02-02 11:29:54.716849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb35327bce1f'
down_revision: Union[str, None] = 'ed14becb7526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_cron_jobs',
    sa.Column('cron_job_id', sa.UUID(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('sessions_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cron_job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_cron_jobs')
    # ### end Alembic commands ###
